version: '3'

services:
    nginx:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./app:/app
          - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    
    php:
      image: php:fpm
      volumes:
          - ./app:/app
          - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
